### ISSUE TITLE
some files gets downloaded in 160kbps only

### ISSUE THREAD

**Issue by AkSachin** [arunKumarNOP/Saavn-Downloader-Android#5]
Some songs with availability of 320kbps quality gets downloaded in 160kbps.

For example this album : https://www.saavn.com/p/album/hindi/Zid-2014/xZZT9ec6oR0_

Above album gives these links which are 160kbps files : 
http://aac.saavncdn.com/722/b224e914e0743a068ed0233bb8d9d81b_160.mp4
http://aac.saavncdn.com/722/5337e7821027f13cc981d7cf4e04b2a1_160.mp4
http://aac.saavncdn.com/722/72c7b694e9162eeef8db127688e86a35_160.mp4
http://aac.saavncdn.com/722/b8fd68dbf4c88c32eebd6624b09a0204_160.mp4
http://aac.saavncdn.com/722/c3c89988add86f63fb14b5e35f0dad7c_160.mp4

However, all these songs are available for 320kbps. (replace 160 with 320 in above links)
I've enabled max quality in settings.

**Comment by arunKumarNOP** [comment]
Ya i experienced it, actually the saavn api returns so that why.

There is "_320kbps" field which tells if the song is available for the song so i download 160 or 320 Kbps song based on that.

Though i think that sometime 320kbps field is misleading, i think i could check if 320 kbps file exist by manually checking it.

I will fix it and update the issue.

**Comment by AkSachin** [comment]
It's working for me !

**Comment by arunKumarNOP** [comment]
Added a new release :)
